apiVersion: asset.sap/v1
kind: Asset
type: mcp-server

metadata:
  name: sap-s4-supplier-invoice-mcp-server
  version: "1.0.0"
  translation: mcp-translation/translation.json
  apiSpec: mcp-translation/api-spec.edmx

provides:
  apis:
    - name: sap-s4-supplier-invoice-mcp-server
      kind: mcp-server
      ordId: customer.build:apiResource:discount-analysis-f8de0.sap-s4-supplier-invoice-mcp-server:v1

requires:
  - name: API_SUPPLIERINVOICE_PROCESS_SRV
    kind: api
    ordId: sap.s4:apiResource:API_SUPPLIERINVOICE_PROCESS_SRV:v1
